### ISSUE TITLE
Running command with a list task

### ISSUE THREAD

**Issue by oLeVanNinh** [huytd/pomoday-v2#13]
I think it is better if it allows running the command with a list task
Example: `d 1 2 3` or `c 1 2 3`

**Comment by huytd** [comment]
Good idea. I'll find sometime to add it this weekend.

**Comment by huytd** [comment]
![2019-11-02 14 27 55](https://user-images.githubusercontent.com/613943/68077287-60029780-fd7e-11e9-9354-b96d0c1941d1.gif)

This is now implemented!
