### ISSUE TITLE
Better way to explain how it works

### ISSUE THREAD

**Issue by imhuyqn** [huytd/pomoday-v2#22]
It took me about 3-5 minutes to start timing a task: 
1. I tried with this command `b abc` naturally after I created a task called `abc` 
2. I thought `b 10` is starting a whole session for 10 mintues.

**Comment by imhuyqn** [comment]
Is it better to show a GIF of how it works?

**Comment by huytd** [comment]
Interesting. Yeah I just finished a blog section on the landing page https://pomoday.com/blog

Probably heading the user to this blog where we can detail all of the usage/example,...
