### ISSUE TITLE
Mobile responsive problem

### ISSUE THREAD

**Issue by qvanphong** [huytd/pomoday-v2#24]
On mobile devices, the orange notification is followed with the page, not with a "command box"

Steps to produce:
- F12 on console
- Click on the responsive icon
- choose Galaxy S5 as a mobile device.

![Untitled](https://user-images.githubusercontent.com/39910970/68087976-49973180-fe8d-11e9-8c9e-9c0f39f6c0b1.png)

**Comment by noitq** [comment]
Cái này vốn sinh ra dành cho người dùng máy tính mà nhỉ: "be productive without leaving your keyboard". Mình nghĩ dùng app này trên điện thoại thì sẽ càng less productive thôi

**Comment by qvanphong** [comment]
> Cái này vốn sinh ra dành cho người dùng máy tính mà nhỉ: "be productive without leaving your keyboard". Mình nghĩ dùng app này trên điện thoại thì sẽ càng less productive thôi

Do mình có sử dụng trên mobile/tablet do làm một số việc trên đó nữa, mặc dù không phải lỗi lớn nhưng mình nghĩ vẫn nên báo cáo lên, nếu nó được sửa vẫn tốt hơn mà đúng ko :D

**Comment by huytd** [comment]
Thanks hai bạn. Lỗi này đã được fixed rồi nha.

Mặc dù đúng là responsive trên mobile cần được fix, vì mục tiêu của mình vẫn là làm cho nó chạy trên mọi device :D
