### ISSUE TITLE
Switch task

### ISSUE THREAD

**Issue by pdxjohnny** [huytd/pomoday-v2#27]
It'd be great to have a command which is a combination of stop work on current task and start work on new task, aka switch tasks.

**Comment by huytd** [comment]
That's a good idea. I'll look into it. Thanks!!

**Comment by pdxjohnny** [comment]
Thank you!! This project is awesome!

**Comment by huytd** [comment]
Switch task now implemented, you can now use it with this syntax:

```
sw[itch] <from-id> <to-id>

For example:

switch 1 2
sw 4 2
```

**Comment by pdxjohnny** [comment]
Thanks!!
