### ISSUE TITLE
Jump to input?

### ISSUE THREAD

**Issue by xmclark** [huytd/pomoday-v2#28]
When I open the page for the first time, I am forced to move my mouse to click the text input at the bottom. 

Is there a jump to input-field hotkey?

**Comment by evandena** [comment]
Mine jumps right to input field.  Using Chrome on Windows 10. 
In the mean time, you might be able to hit tab and jump to the input field.

**Comment by huytd** [comment]
Yes it should behave as what @evandena described from the beginning.

But I've seen many people reported the same issue as well. Maybe it worth take a closer look.

Meanwhile, could you please provide more information about what setup you're using? @xmclark 

- What browser you're on?
- Do you use any keyboard manipulating addons, like Vim-mode?
- Any ads blocker?

**Comment by xmclark** [comment]
Windows 10, Firefox 70.0.1 (64-bit) in private window.

`Tab-key` key does provide a solution for me. 

Hitting it multiple times will cause other items to focus in my browser. Still would be nice if there was a dedicated key like `s-key` on crates.io's search bar.

**Comment by xmclark** [comment]
@huytd  @evandena would you be open to that kind of addition to pomoday?

**Comment by huytd** [comment]
Sound like a good plan. Instead of `S` (search), how about `i` (input)? @xmclark

**Comment by xmclark** [comment]
yeah I don't care. `i` works for me. I'm happy to PR this.

**Comment by huytd** [comment]
That would be great! Thanks!

**Comment by huytd** [comment]
With PR #32 merged. I think we can close this issue now.
