### ISSUE TITLE
Enable some kind of markdown for links

### ISSUE THREAD

**Issue by janjur** [huytd/pomoday-v2#29]
Hi! That'd be great if I could give a title to a link, [like this](https://youtu.be/dQw4w9WgXcQ), so task is shorter :)

**Comment by huytd** [comment]
Hi @janjur, markdown should be supported out of the box already.

Could you try something like this?

![](https://i.imgur.com/2fcom7f.png)

**Comment by janjur** [comment]
right, it works :)
