### ISSUE TITLE
History for entered commands

### ISSUE THREAD

**Issue by hgoldstein** [huytd/pomoday-v2#4]
It would be nice to have some sort of history for the entered commands. Mainly my issue was that, while starting out, I forgot to prepend my command with `t`, so I entered something like:
```
@code somewhat long task name ...
```
Then hit enter and watched it disappear into the void. I'd like to be able to hit "up" on the keyboard and just prepend a `t`.

**Comment by ff4500** [comment]
Using the up/down arrows, (like in shell histroy) would be great.

**Comment by huytd** [comment]
Yes, this can be a better approach, since I'm planning for tag auto completion.

It can be designed to work more like Fish shell autocompletion. Great idea.

Thanks guy! I'll add this to the roadmap.

**Comment by huytd** [comment]
I just implemented a more simple version, just as suggested in the first comment.

Now you can press UP or DOWN (or Ctrl + P / Ctrl + N in Emacs's way) to retrieve the previously entered commands.
