### ISSUE TITLE
How do I remember a task I archived? 

### ISSUE THREAD

**Issue by imhuyqn** [huytd/pomoday-v2#40]
Currently there is no way to see a list of archived tasks. It's difficult to remember the id of the tasks after a while. Isn't it better for users to have a place to see a list of archived tasks? So it's easier for them to remember/search for archived tasks and restore them.

**Comment by imhuyqn** [comment]
I think the app should have a button like "more" along with other tags like "done", "in progress", etc so you can see how many archived tasks the user has. Currently design make it easy to forget that we don't have a list of archived tasks or not knowing of its existence.

**Comment by huytd** [comment]
You can show the list of archived task by typing ‘list-archived’, you can
also unarchive a task by running archive command again on that task.

I’m working on a better help page in app and a list of command showing as
you type. Hope that help!
