### ISSUE TITLE
All task gone if it was added when help window is turn on 

### ISSUE THREAD

**Issue by thepapercoder** [huytd/pomoday-v2#41]
## How to reproduce:
- Run pomoday-v2 app
- Turn on help window
- Add some tasks
- Press exit to close the help window

After this you will see all the tasks was added are gone!

**Comment by huytd** [comment]
Thanks. I’ve noticed this as well. I’m having some updates that won’t allow
adding task when help is on. I’ll test again if this issue still
reproducible.

**Comment by huytd** [comment]
Now it's fixed. You won't be able to open command bar in Help anymore.
