### ISSUE TITLE
Should show current content (or suggestion) while updating

### ISSUE THREAD

**Issue by jinhduong** [huytd/pomoday-v2#44]
Hi,

Sometimes we only need to change a few characters in current task content but now we have to re-type all of them.

Suggestion:
`e 1 <show current content>`

**Comment by huytd** [comment]
Good idea. I'll add it.

**Comment by huytd** [comment]
Fixed. Here's how it looks:

![Kapture 2019-11-29 at 17 27 42](https://user-images.githubusercontent.com/613943/69893980-c1f6e400-12cd-11ea-8079-a89cebe1d05a.gif)
