### ISSUE TITLE
Support #tag in task content

### ISSUE THREAD

**Issue by jinhduong** [huytd/pomoday-v2#45]
Hi,

Could we support #tag and then filter by these values later? such as we have some task with a guy name is `Hau`, I would like to search which tasks have done with him ㊙️ 

Suggestion:
`t @personal go to #aHau home at weekend`

**Comment by huytd** [comment]
I think what you need is an actual task search/filter feature, right?

It will be for anything, not just a hashtag, but yeah, I can highlight hashtag for more visibility.

**Comment by huytd** [comment]
Here's how it looks in light theme
![image](https://user-images.githubusercontent.com/613943/69891580-581d1100-12b2-11ea-9a2d-ccf38cbd85a0.png)

And dark theme
![image](https://user-images.githubusercontent.com/613943/69891586-5d7a5b80-12b2-11ea-8e1d-4896b7debd77.png)

**Comment by huytd** [comment]
This is how the search functionality look like:

![Kapture 2019-11-29 at 15 31 39](https://user-images.githubusercontent.com/613943/69892733-a552b000-12bd-11ea-8bf3-f832917e2e15.gif)
