### ISSUE TITLE
How is switch working

### ISSUE THREAD

**Issue by deepDiverPaul** [huytd/pomoday-v2#46]
First: This is a solution I was trying to find for a long time. Thank you very much for your effort!

Is the __switch__ command implemented yet. It would be incredible if I could switch my timetracking to another task.

Many Thanks.

**Comment by deepDiverPaul** [comment]
Never mind. I thought parsing only the task id  where i want to switch to is enough.

Actual working syntax to switch from task 8 to 3: `sw 8 3`

**Comment by huytd** [comment]
Yeah the thing is, we could have many running tasks at the same time, so we have to pass in a task we want to jump from.
