### ISSUE TITLE
Option to make the command bar sticky

### ISSUE THREAD

**Issue by leira-sanchez** [huytd/pomoday-v2#48]
It's annoying having to click 'i' every time I want to do something. I liked it always there like before. 

I also preferred it at the bottom.

**Comment by huytd** [comment]
There is a typeahead feature planned, so instead of pressing i all the
time, you can just start typing right away. Would that work?

About the position, I’ll make it configurable.

**Comment by leira-sanchez** [comment]
Yes, that would work great! Thank you. I love this app and use it everyday :)

**Comment by huytd** [comment]
Thank you so much!!

**Comment by huytd** [comment]
This is now fixed with https://github.com/huytd/pomoday-v2/commit/f7facb96d8734262a60f329fd9ff28915414b313

The new command is: `setting` or just click on the cogs icon on the top right of the app.

In here, you'll have an option to toggle sticky command bar.
