### ISSUE TITLE
Sync seems buggy

### ISSUE THREAD

**Issue by jinhduong** [huytd/pomoday-v2#50]
This morning, I created a new task and then a bit moment later (the sync just ran), after that the task I just created was disappeared. 🤔

**Comment by huytd** [comment]
I made a commit (hoping) to fix that issue https://github.com/huytd/pomoday-v2/commit/01b3ebfd016a1e9d9776be532643c9657469e918 and I think it's after when you tested it.

Could you do a hard refresh and try some more time and let me know how often it's happening again please? :D

**Comment by huytd** [comment]
General feedback indicated that the issue isn't happening anymore.

Please feel free to reopen this ticket if you still notice the issue.
