### ISSUE TITLE
Tag Auto-Complete

### ISSUE THREAD

**Issue by leira-sanchez** [huytd/pomoday-v2#66]
Enable tag only auto-complete. It'll suggest auto-complete of other tasks I've already added. I would like tags to auto-complete but not the whole task, just the tag part. That way, I can save time creating tasks for the same tag over and over again.

**Comment by huytd** [comment]
For now, if you added two tasks with the same tag, the auto complete will be reduced to tag only, for example:

```
# first one
@pomoday Fix that bug
# second one
@pomoday Add that feature
```
