### ISSUE TITLE
Docker datastore

### ISSUE THREAD

**Issue by rorph** [huytd/pomoday-v2#70]
Question:

Where persistent data is stored in the docker version ?

I see no volume mounts, is data stored in the browser? Is there a way to enable persistent datastorage so it works across multiple devices?

Thanks!

**Comment by huytd** [comment]
Yes, data is saved to browser's localStorage.

If you want to have your data saved on some server, the frontend has already implemented the API interface to do so, but you'll need to implement the backend yourself using the following specs https://github.com/huytd/pomoday-v2/wiki/Pomoday-Backend-API-Specification

(Sorry but I dont have the public backend implemented yet)
